function adminActionButtons(kind,id,name){return `<div class="section-actions"><button type="button" class="secondary" onclick="adminEdit('${kind}','${esc(id)}')">Rregullo</button><button type="button" class="secondary" onclick="adminDelete('${kind}','${esc(id)}','${esc(name)}')">Fshij</button></div>`}
function adminTable(headers,rows,addLabel,onAdd){$('moduleContent').innerHTML=`<div class="section-actions" style="margin-bottom:14px"><button class="primary" id="dynamicAdd">+ ${esc(addLabel)}</button></div><div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(v=>v).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty-state">Nuk ka të dhëna.</td></tr>`}</tbody></table></div>`;$('resultCount').textContent=`${rows.length} rezultate reale`;$('dynamicAdd').onclick=onAdd}
async function schools(){const d=await api('/api/v1/management/schools');adminTable(['ID','Shkolla','Adresa','Statusi','Veprime'],d.map(x=>[`<td>${esc(x.id)}</td>`,`<td>${esc(x.name)}</td>`,`<td>${esc(x.address||'')}</td>`,`<td>${x.active?'Aktive':'Joaktive'}</td>`,`<td>${adminActionButtons('school',x.id,x.name)}</td>`]),'Shto shkollë',()=>schoolForm())}
async function subjects(){const d=await api('/api/v1/management/subjects');adminTable(['ID','Lënda','Kodi','Statusi','Veprime'],d.map(x=>[`<td>${esc(x.id)}</td>`,`<td>${esc(x.name)}</td>`,`<td>${esc(x.code||'')}</td>`,`<td>${x.active?'Aktive':'Joaktive'}</td>`,`<td>${adminActionButtons('subject',x.id,x.name)}</td>`]),'Shto lëndë',()=>subjectForm())}
async function teachers(){const d=await api('/api/v1/management/teachers');adminTable(['ID','Mësimdhënësi','Lënda kryesore','Përdoruesi','Klasa','Statusi','Veprime'],d.map(x=>[`<td>${esc(x.id)}</td>`,`<td>${esc(x.fullName)}</td>`,`<td>${esc(x.subjectId)}</td>`,`<td>${esc(x.username)}</td>`,`<td>${esc((x.classIds||[]).join(', ')||'—')}</td>`,`<td>${x.active?'Aktiv':'Joaktiv'}</td>`,`<td>${adminActionButtons('teacher',x.id,x.fullName)}</td>`]),'Shto mësimdhënës',()=>teacherForm())}
async function students(admin=false){const d=await api('/api/v1/management/students');if(!admin){return window.__originalStudents?window.__originalStudents(false):null}adminTable(['ID','Emri','Klasa','Datëlindja','Statusi','Veprime'],d.map(x=>[`<td>${esc(x.id)}</td>`,`<td>${esc(x.fullName)}</td>`,`<td>${esc(x.className)}</td>`,`<td>${esc(x.birthDate)}</td>`,`<td>${x.active?'Aktiv':'Joaktiv'}</td>`,`<td>${adminActionButtons('student',x.id,x.fullName)}</td>`]),'Shto nxënës',()=>studentForm())}
async function users(){const d=await api('/api/v1/management/users');adminTable(['ID','Përdoruesi','Emri','Roli','Statusi','Veprime'],d.map(x=>[`<td>${esc(x.id)}</td>`,`<td>${esc(x.username)}</td>`,`<td>${esc(x.fullName)}</td>`,`<td>${esc(roles[x.role]||x.role)}</td>`,`<td>${x.active?'Aktiv':'Joaktiv'}</td>`,`<td>${adminActionButtons('user',x.id,x.fullName)}</td>`]),'Krijo përdorues dhe cakto rol',()=>userForm())}
function adminEdit(kind,id){if(kind==='school')return editSchool(id);if(kind==='subject')return editSubject(id);if(kind==='teacher')return editTeacher(id);if(kind==='student')return editStudent(id);if(kind==='user')return editUser(id)}
async function adminDelete(kind,id,name){if(!confirm(`A jeni i sigurt që doni ta fshini ${kindLabel(kind)} "${name}"?\n\nKy veprim do ta çaktivizojë të dhënën dhe nuk do të fshijë historikun.`))return;try{const path={school:'/api/v1/management/schools/',subject:'/api/v1/management/subjects/',teacher:'/api/v1/management/teachers/',student:'/api/v1/management/students/',user:'/api/v1/management/users/'}[kind];await api(path+encodeURIComponent(id),{method:'DELETE'});await openModule(currentModule)}catch(e){alert(e.message)}}
function kindLabel(k){return {school:'shkollën',subject:'lëndën',teacher:'mësimdhënësin',student:'nxënësin',user:'përdoruesin'}[k]||'të dhënën'}
async function editSchool(id){const d=await api('/api/v1/management/schools');const x=d.find(v=>v.id===id);if(!x)return;modal('Rregullo shkollën',field('name','Emri i shkollës','text',`required value="${esc(x.name)}"`)+field('address','Adresa','text',`value="${esc(x.address||'')}"`),async f=>api(`/api/v1/management/schools/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({name:f.get('name'),address:f.get('address')})}))}
async function editSubject(id){const d=await api('/api/v1/management/subjects');const x=d.find(v=>v.id===id);if(!x)return;modal('Rregullo lëndën',field('name','Emri i lëndës','text',`required value="${esc(x.name)}"`)+field('code','Kodi','text',`value="${esc(x.code||'')}"`),async f=>api(`/api/v1/management/subjects/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({name:f.get('name'),code:f.get('code')})}))}
async function editTeacher(id){const [d,s]=await Promise.all([api('/api/v1/management/teachers'),api('/api/v1/management/subjects')]);const x=d.find(v=>v.id===id);if(!x)return;modal('Rregullo mësimdhënësin',field('fullName','Emri dhe mbiemri','text',`required value="${esc(x.fullName)}"`)+field('username','Përdoruesi','text',`required value="${esc(x.username)}"`)+`<label>Lënda kryesore<select name="subjectId" required>${s.map(v=>`<option value="${esc(v.id)}" ${v.id===x.subjectId?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label>`,async f=>api(`/api/v1/management/teachers/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({fullName:f.get('fullName'),username:f.get('username'),subjectId:f.get('subjectId')})}))}
async function editStudent(id){const [d,c]=await Promise.all([api('/api/v1/management/students'),api('/api/v1/management/classes')]);const x=d.find(v=>v.id===id);if(!x)return;modal('Rregullo nxënësin',field('fullName','Emri dhe mbiemri','text',`required value="${esc(x.fullName)}"`)+field('birthDate','Datëlindja','date',`required value="${esc(x.birthDate)}"`)+`<label>Klasa / paralelja<select name="classId" required>${c.map(v=>`<option value="${esc(v.id)}" ${v.id===x.classId?'selected':''}>${esc(v.name)} — ${esc(v.gradeLevel)}</option>`).join('')}</select></label>`,async f=>api(`/api/v1/management/students/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({fullName:f.get('fullName'),birthDate:f.get('birthDate'),classId:f.get('classId')})}))}
async function editUser(id){const d=await api('/api/v1/management/users');const x=d.find(v=>v.id===id);if(!x)return;modal('Rregullo përdoruesin',field('username','Përdoruesi','text',`required value="${esc(x.username)}"`)+field('fullName','Emri dhe mbiemri','text',`required value="${esc(x.fullName)}"`)+`<label>Roli<select name="role" required>${Object.entries(roles).map(([k,v])=>`<option value="${k}" ${k===x.role?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Statusi<select name="active"><option value="true" ${x.active?'selected':''}>Aktiv</option><option value="false" ${!x.active?'selected':''}>Joaktiv</option></select></label>`,async f=>api(`/api/v1/management/users/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({username:f.get('username'),fullName:f.get('fullName'),role:f.get('role'),active:f.get('active')==='true'})}))}
