const API_BASE=window.location.origin;let token=localStorage.getItem('eshkolla_token')||'',currentUser=null,currentModule='';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const roles={ADMINISTRATOR:'Administrator',DREJTOR:'Drejtor',MESIMDHENES:'Mësimdhënës',NXENES:'Nxënës',PRIND:'Prind'};const icons={schools:'🏫',classes:'📚',subjects:'📘',teachers:'👨‍🏫',students:'🎓',assignments:'🔗',users:'👥',grades:'⭐',absences:'🕒'};
async function api(path,opt={}){const h={Accept:'application/json',...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(API_BASE+path,{...opt,headers:h}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d=t}if(r.status===401){token='';localStorage.removeItem('eshkolla_token');showLogin('Sesioni nuk është më i vlefshëm.');throw Error('UNAUTHORIZED')}if(!r.ok)throw Error(d?.message||d?.error||`Gabim ${r.status}`);return d}
function showLogin(msg=''){ $('login').classList.remove('hidden');$('dashboard').classList.add('hidden');$('error').textContent=msg }
async function login(){const username=$('username').value.trim(),password=$('password').value;$('error').textContent='';if(!username||!password){$('error').textContent='Plotësoni përdoruesin dhe fjalëkalimin.';return}$('loginButton').disabled=true;$('loginButton').textContent='Duke u kyçur...';try{const r=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,password})});token=r.token;currentUser=r.user;localStorage.setItem('eshkolla_token',token);await dashboard()}catch(e){$('error').textContent=e.message==='Failed to fetch'?'Serveri nuk është i arritshëm.':e.message}finally{$('loginButton').disabled=false;$('loginButton').textContent='Hyr'}}
async function logout(){try{await api('/api/v1/auth/logout',{method:'POST'})}catch(_){}token='';currentUser=null;localStorage.removeItem('eshkolla_token');showLogin('')}
async function dashboard(){ $('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('welcome').textContent=`Mirë se vini, ${currentUser.fullName}`;$('roleDescription').textContent=`Qasje reale — ${roles[currentUser.role]||currentUser.role}`;$('profile').innerHTML=`<div><span>Përdoruesi</span><strong>${esc(currentUser.username)}</strong></div><div><span>Emri</span><strong>${esc(currentUser.fullName)}</strong></div><div><span>Roli</span><strong>${esc(roles[currentUser.role]||currentUser.role)}</strong></div><div><span>Statusi</span><strong>Aktiv</strong></div>`;const mods=currentUser.role==='ADMINISTRATOR'?adminModules():baseModules();$('modules').innerHTML=mods.map(m=>`<button class="module-card" data-module="${m[0]}"><span class="module-icon">${icons[m[0]]}</span><span><strong>${m[1]}</strong><small>${m[2]}</small></span><span class="arrow">→</span></button>`).join('');document.querySelectorAll('.module-card').forEach(b=>b.onclick=()=>openModule(b.dataset.module));try{const [s,c,g,a]=await Promise.all([api('/api/v1/students?page=1&pageSize=1'),api('/api/v1/classes'),api('/api/v1/grades'),api('/api/v1/absences')]);$('stats').innerHTML=[['Nxënës',s.total??s.items?.length??0],['Klasat',c.length],['Nota',g.length],['Mungesa',a.length]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');}catch(e){console.error(e)}}
function baseModules(){return [['classes','Klasat','Të dhënat reale'],['students','Nxënësit','Regjistri real'],['grades','Notat','Të dhënat reale'],['absences','Mungesat','Evidenca reale']]}
function adminModules(){return [['schools','Shkollat','Shto dhe menaxho shkollat'],['classes','Klasat & paralelet','Krijo klasa dhe lidhi me shkollën'],['subjects','Lëndët','Menaxho lëndët mësimore'],['teachers','Mësimdhënësit','Krijo dhe menaxho mësimdhënësit'],['students','Nxënësit','Shto dhe menaxho nxënësit'],['assignments','Caktimet','Lëndë + klasë + mësimdhënës'],['users','Përdoruesit & rolet','Admin cakton rolet dhe lidhjet'],['grades','Notat','Të dhënat reale'],['absences','Mungesat','Evidenca reale']]} 
async function openModule(m){currentModule=m;if(['students','grades','absences'].includes(m)){if(currentUser?.role==='ADMINISTRATOR'){window.adminStudentsClassId='';window.adminGradesClassId='';window.adminAbsencesClassId='';}if(currentUser?.role==='MESIMDHENES'){window.teacherStudentsClassId='';window.webGradesClassId='';window.webGradesSubjectId='';window.teacherAbsencesClassId='';}}$('modules').classList.add('hidden');$('moduleView').classList.remove('hidden');$('moduleTitle').textContent={schools:'Shkollat',classes:'Klasat & paralelet',subjects:'Lëndët mësimore',teachers:'Mësimdhënësit',students:'Nxënësit',assignments:'Caktimet e mësimdhënësve',users:'Përdoruesit & rolet',grades:'Notat',absences:'Mungesat'}[m];$('moduleControls').classList.toggle('hidden',['profile','schools','subjects','teachers','assignments','users'].includes(m));$('addStudentButton').classList.add('hidden');try{if(m==='schools')await schools();else if(m==='classes')await classes(true);else if(m==='subjects')await subjects();else if(m==='teachers')await teachers();else if(m==='students')await students(true);else if(m==='assignments')await assignments();else if(m==='users')await users();else if(m==='grades')await grades();else if(m==='absences')await absences()}catch(e){$('moduleContent').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function table(h,rows){$('moduleContent').innerHTML=`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${h.length}" class="empty-state">Nuk ka të dhëna.</td></tr>`}</tbody></table></div>`;$('resultCount').textContent=`${rows.length} rezultate reale`}
function addButton(label,onClick){$('moduleContent').insertAdjacentHTML('afterbegin',`<div class="section-actions" style="margin-bottom:14px"><button class="primary" id="dynamicAdd">+ ${esc(label)}</button></div>`);$('dynamicAdd').onclick=onClick}
async function schools(){const d=await api('/api/v1/management/schools');table(['ID','Shkolla','Adresa','Statusi'],d.map(x=>[x.id,x.name,x.address||'',x.active?'Aktive':'Joaktive']));addButton('Shto shkollë',()=>schoolForm())}
async function subjects(){const d=await api('/api/v1/management/subjects');table(['ID','Lënda','Kodi','Statusi'],d.map(x=>[x.id,x.name,x.code||'',x.active?'Aktive':'Joaktive']));addButton('Shto lëndë',()=>subjectForm())}
async function classes(admin=false){const d=await api('/api/v1/management/classes');table(['ID','Klasa/paralelja','Niveli','Nxënës','Mësimdhënës'],d.map(x=>[x.id,x.name,x.gradeLevel,x.studentCount,(x.teacherIds||[]).join(', ')||'—']));if(admin)addButton('Shto klasë/paralele',()=>classForm())}
async function teachers(){const d=await api('/api/v1/management/teachers');table(['ID','Mësimdhënësi','Lënda kryesore','Përdoruesi','Klasa','Statusi'],d.map(x=>[x.id,x.fullName,x.subjectId,x.username,(x.classIds||[]).join(', ')||'—',x.active?'Aktiv':'Joaktiv']));addButton('Shto mësimdhënës',()=>teacherForm())}
async function students(admin=false){const q=$('tableSearch').value.trim();const d=admin?await api('/api/v1/management/students'):await api('/api/v1/students?page=1&pageSize=100'+(q?'&search='+encodeURIComponent(q):''));const rows=admin?d.map(x=>[x.id,x.fullName,x.className,x.birthDate,x.active?'Aktiv':'Joaktiv']):(d.items||[]).map(x=>[x.id,x.fullName,x.classId,x.birthDate,x.isActive?'Aktiv':'Joaktiv']);table(['ID','Emri','Klasa','Datëlindja','Statusi'],rows);if(admin)addButton('Shto nxënës',()=>studentForm())}
async function assignments(){const [d,t,s,c]=await Promise.all([api('/api/v1/management/teacher-subject-assignments'),api('/api/v1/management/teachers'),api('/api/v1/management/subjects'),api('/api/v1/management/classes')]);table(['Mësimdhënësi','Lënda','Klasa/paralelja'],d.map(x=>[x.teacherName,x.subjectName,x.className]));addButton('Cakto mësimdhënës + lëndë + klasë',()=>assignmentForm(t,s,c))}
async function users(){const d=await api('/api/v1/management/users');table(['ID','Përdoruesi','Emri','Roli','Statusi'],d.map(x=>[x.id,x.username,x.fullName,roles[x.role]||x.role,x.active?'Aktiv':'Joaktiv']));addButton('Krijo përdorues dhe cakto rol',()=>userForm())}
async function grades(){const d=await api('/api/v1/grades');table(['Nxënësi','Lënda','Nota','Periudha','Viti'],d.map(x=>[x.studentId,x.subjectId,x.value,x.period,x.academicYear]))}
async function absences(){const d=await api('/api/v1/absences');table(['Nxënësi','Lënda','Data','Statusi','Shënim'],d.map(x=>[x.studentId,x.subjectId,x.date,x.status,x.note||'']))}
function profile(){$('moduleContent').innerHTML=`<div class="profile-grid"><div><span>ID</span><strong>${esc(currentUser.id)}</strong></div><div><span>Përdoruesi</span><strong>${esc(currentUser.username)}</strong></div><div><span>Emri</span><strong>${esc(currentUser.fullName)}</strong></div><div><span>Roli</span><strong>${esc(roles[currentUser.role]||currentUser.role)}</strong></div></div>`}
function modal(title,body,onSubmit){const wrap=document.createElement('div');wrap.className='modal';wrap.innerHTML=`<div class="modal-card"><div class="section-title"><h3>${esc(title)}</h3><button class="secondary" id="closeModal">Mbyll</button></div><form id="adminForm" class="form-grid">${body}<div class="form-actions"><button type="button" class="secondary" id="cancelModal">Anulo</button><button type="submit" class="primary">Ruaj</button></div><p id="formError" class="error"></p></form></div>`;document.body.appendChild(wrap);const close=()=>wrap.remove();$('closeModal').onclick=close;$('cancelModal').onclick=close;wrap.querySelector('#adminForm').onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.target));close();await openModule(currentModule)}catch(err){wrap.querySelector('#formError').textContent=err.message}}}
function field(name,label,type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" ${extra}></label>`}
function schoolForm(){modal('Shto shkollë',field('name','Emri i shkollës','text','required')+field('address','Adresa','text'),async f=>api('/api/v1/management/schools',{method:'POST',body:JSON.stringify({name:f.get('name'),address:f.get('address')})}))}
function subjectForm(){modal('Shto lëndë',field('name','Emri i lëndës','text','required')+field('code','Kodi'),async f=>api('/api/v1/management/subjects',{method:'POST',body:JSON.stringify({name:f.get('name'),code:f.get('code')})}))}
async function classForm(){const schools=await api('/api/v1/management/schools');modal('Shto klasë / paralele',field('name','Emri, p.sh. 8-A','text','required')+field('gradeLevel','Niveli','number','min="1" max="13" required')+`<label>Shkolla<select name="schoolId"><option value="">Pa shkollë</option>${schools.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label>`,async f=>api('/api/v1/management/classes',{method:'POST',body:JSON.stringify({name:f.get('name'),gradeLevel:Number(f.get('gradeLevel')),schoolId:f.get('schoolId')||null})}))}
async function teacherForm(){const subjects=await api('/api/v1/management/subjects');modal('Shto mësimdhënës',field('fullName','Emri dhe mbiemri','text','required')+field('username','Përdoruesi','text','required')+field('password','Fjalëkalimi','password','minlength="10" required')+`<label>Lënda kryesore<select name="subjectId" required>${subjects.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label>`,async f=>api('/api/v1/management/users',{method:'POST',body:JSON.stringify({username:f.get('username'),fullName:f.get('fullName'),password:f.get('password'),role:'MESIMDHENES',subjectId:f.get('subjectId')})}))}
async function studentForm(){const classes=await api('/api/v1/management/classes');modal('Shto nxënës',field('fullName','Emri dhe mbiemri','text','required')+field('birthDate','Datëlindja','date','required')+`<label>Klasa / paralelja<select name="classId" required>${classes.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.gradeLevel)}</option>`).join('')}</select></label>`,async f=>api('/api/v1/management/students',{method:'POST',body:JSON.stringify({fullName:f.get('fullName'),birthDate:f.get('birthDate'),classId:f.get('classId')})}))}
async function assignmentForm(teachers,subjects,classes){modal('Cakto mësimdhënësin',`<label>Mësimdhënësi<select name="teacherId" required>${teachers.map(x=>`<option value="${esc(x.id)}">${esc(x.fullName)} — ${esc(x.username)}</option>`).join('')}</select></label><label>Lënda<select name="subjectId" required>${subjects.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label><label>Klasa / paralelja<select name="classId" required>${classes.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.gradeLevel)}</option>`).join('')}</select></label>`,async f=>api('/api/v1/management/teacher-subject-assignments',{method:'POST',body:JSON.stringify({teacherId:f.get('teacherId'),subjectId:f.get('subjectId'),classId:f.get('classId')})}))}
async function userForm(){const students=await api('/api/v1/management/students');modal('Krijo përdorues dhe cakto rol',field('fullName','Emri dhe mbiemri','text','required')+field('username','Përdoruesi','text','required')+field('password','Fjalëkalimi','password','minlength="10" required')+`<label>Roli<select name="role" required><option value="DREJTOR">Drejtor</option><option value="MESIMDHENES">Mësimdhënës</option><option value="NXENES">Nxënës</option><option value="PRIND">Prind</option><option value="ADMINISTRATOR">Administrator</option></select></label><label>Studenti i lidhur për Nxënës/Prind<select name="studentId"><option value="">Zgjidhni...</option>${students.map(x=>`<option value="${esc(x.id)}">${esc(x.fullName)} — ${esc(x.className)}</option>`).join('')}</select></label>`,async f=>{const role=f.get('role');let payload={username:f.get('username'),fullName:f.get('fullName'),password:f.get('password'),role};if(role==='NXENES'||role==='PRIND')payload.studentId=f.get('studentId');return api('/api/v1/management/users',{method:'POST',body:JSON.stringify(payload)})})}
$('loginButton').onclick=login;$('logoutButton').onclick=logout;$('password').addEventListener('keydown',e=>e.key==='Enter'&&login());$('username').addEventListener('keydown',e=>e.key==='Enter'&&login());$('backButton').onclick=()=>{$('moduleView').classList.add('hidden');$('modules').classList.remove('hidden')};$('tableSearch').addEventListener('input',()=>currentModule==='students'&&students(false));$('clearFilters').onclick=()=>{$('tableSearch').value='';if(currentModule==='students')students(false)};(async()=>{if(token)try{currentUser=await api('/api/v1/auth/me');await dashboard()}catch(_){showLogin('')}})();
