const API_BASE=window.location.origin;let token=localStorage.getItem('eshkolla_token')||'',currentUser=null,currentModule='';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const roles={ADMINISTRATOR:'Administrator',DREJTOR:'Drejtor',MESIMDHENES:'Mësimdhënës',NXENES:'Nxënës',PRIND:'Prind'};const icons={classes:'📚',students:'🎓',grades:'⭐',absences:'🕒',profile:'👤'};
async function api(path,opt={}){const h={Accept:'application/json',...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(API_BASE+path,{...opt,headers:h}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(_){d=t}if(r.status===401){token='';localStorage.removeItem('eshkolla_token');showLogin('Sesioni nuk është më i vlefshëm.');throw Error('UNAUTHORIZED')}if(!r.ok)throw Error(d?.message||d?.error||`Gabim ${r.status}`);return d}
function showLogin(msg=''){ $('login').classList.remove('hidden');$('dashboard').classList.add('hidden');$('status').textContent='Jo i kyçur';$('status').className='status';$('error').textContent=msg }
async function login(){const username=$('username').value.trim(),password=$('password').value;$('error').textContent='';if(!username||!password){$('error').textContent='Plotësoni përdoruesin dhe fjalëkalimin.';return}$('loginButton').disabled=true;$('loginButton').textContent='Duke u kyçur...';try{const r=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,password})});token=r.token;currentUser=r.user;localStorage.setItem('eshkolla_token',token);await dashboard()}catch(e){$('error').textContent=e.message==='Failed to fetch'?'Serveri nuk është i arritshëm.':e.message}finally{$('loginButton').disabled=false;$('loginButton').textContent='Hyr'}}
async function logout(){try{await api('/api/v1/auth/logout',{method:'POST'})}catch(_){}token='';currentUser=null;localStorage.removeItem('eshkolla_token');showLogin('')}
async function dashboard(){ $('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('status').textContent='I kyçur';$('status').className='status success';$('welcome').textContent=`Mirë se vini, ${currentUser.fullName}`;$('roleDescription').textContent=`Qasje reale — ${roles[currentUser.role]||currentUser.role}`;$('profile').innerHTML=`<div><span>Përdoruesi</span><strong>${esc(currentUser.username)}</strong></div><div><span>Emri</span><strong>${esc(currentUser.fullName)}</strong></div><div><span>Roli</span><strong>${esc(roles[currentUser.role]||currentUser.role)}</strong></div><div><span>Statusi</span><strong>Aktiv</strong></div>`;const mods=[['classes','Klasat','Të dhënat reale'],['students','Nxënësit','Regjistri real'],['grades','Notat','Të dhënat reale'],['absences','Mungesat','Evidenca reale'],['profile','Profili','Llogaria']];$('modules').innerHTML=mods.map(m=>`<button class="module-card" data-module="${m[0]}"><span class="module-icon">${icons[m[0]]}</span><span><strong>${m[1]}</strong><small>${m[2]}</small></span><span class="arrow">→</span></button>`).join('');document.querySelectorAll('.module-card').forEach(b=>b.onclick=()=>openModule(b.dataset.module));try{const [s,c,g,a]=await Promise.all([api('/api/v1/students?page=1&pageSize=1'),api('/api/v1/classes'),api('/api/v1/grades'),api('/api/v1/absences')]);$('stats').innerHTML=[['Nxënës',s.total??s.items?.length??0],['Klasat',c.length],['Nota',g.length],['Mungesa',a.length]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('activityList').innerHTML=['API: aktive','PostgreSQL/Neon: aktive','Autentikimi: real'].map(x=>`<div class="activity"><span class="dot"></span><span>${x}</span><small>Aktive</small></div>`).join('')}catch(e){$('activityList').innerHTML=`<div class="activity"><span class="dot"></span><span>${esc(e.message)}</span></div>`}}
async function openModule(m){currentModule=m;$('modules').classList.add('hidden');$('moduleView').classList.remove('hidden');$('moduleTitle').textContent={classes:'Klasat',students:'Nxënësit',grades:'Notat',absences:'Mungesat',profile:'Profili'}[m];$('moduleControls').classList.toggle('hidden',m==='profile');$('addStudentButton').classList.add('hidden');try{if(m==='classes')await classes();else if(m==='students')await students();else if(m==='grades')await grades();else if(m==='absences')await absences();else profile()}catch(e){$('moduleContent').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function table(h,rows){$('moduleContent').innerHTML=`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${h.length}" class="empty-state">Nuk ka të dhëna.</td></tr>`}</tbody></table></div>`;$('resultCount').textContent=`${rows.length} rezultate reale`}
async function classes(){const d=await api('/api/v1/classes');table(['ID','Klasa','Niveli','Mësimdhënësi','Nxënës'],d.map(x=>[x.id,x.name,x.gradeLevel,x.teacherId,x.studentCount]))}
async function students(){const q=$('tableSearch').value.trim(),d=await api('/api/v1/students?page=1&pageSize=100'+(q?'&search='+encodeURIComponent(q):''));table(['ID','Emri','Klasa','Datëlindja','Statusi'],(d.items||[]).map(x=>[x.id,x.fullName,x.classId,x.birthDate,x.isActive?'Aktiv':'Joaktiv']))}
async function grades(){const d=await api('/api/v1/grades');table(['Nxënësi','Lënda','Nota','Periudha','Viti'],d.map(x=>[x.studentId,x.subjectId,x.value,x.period,x.academicYear]))}
async function absences(){const d=await api('/api/v1/absences');table(['Nxënësi','Lënda','Data','Statusi','Shënim'],d.map(x=>[x.studentId,x.subjectId,x.date,x.status,x.note||'']))}
function profile(){$('moduleContent').innerHTML=`<div class="profile-grid"><div><span>ID</span><strong>${esc(currentUser.id)}</strong></div><div><span>Përdoruesi</span><strong>${esc(currentUser.username)}</strong></div><div><span>Emri</span><strong>${esc(currentUser.fullName)}</strong></div><div><span>Roli</span><strong>${esc(roles[currentUser.role]||currentUser.role)}</strong></div></div>`}
$('loginButton').onclick=login;$('logoutButton').onclick=logout;$('password').addEventListener('keydown',e=>e.key==='Enter'&&login());$('username').addEventListener('keydown',e=>e.key==='Enter'&&login());$('backButton').onclick=()=>{$('moduleView').classList.add('hidden');$('modules').classList.remove('hidden')};$('tableSearch').addEventListener('input',()=>currentModule==='students'&&students());$('clearFilters').onclick=()=>{$('tableSearch').value='';if(currentModule==='students')students()};(async()=>{if(token)try{currentUser=await api('/api/v1/auth/me');await dashboard()}catch(_){showLogin('')}})();