// Demo profili i Leonard Tahiraj — Mësimdhënës i Matematikës.
demoUsers.mesimdhenes.fullName = "Leonard Tahiraj";
demoUsers["leonard.tahiraj"] = { ...demoUsers.mesimdhenes, username: "leonard.tahiraj", fullName: "Leonard Tahiraj", roleLabel: "Mësimdhënës i Matematikës" };
data.users[2] = ["3", "Leonard Tahiraj", "leonard.tahiraj", "Mësimdhënës", "Aktiv"];
data.teachers[0] = ["M001", "Leonard Tahiraj", "Matematikë", "T-1001", "Aktiv"];
data.teacherGrades = [["Ardit Krasniqi","VIII/1","Matematikë","Test","5","Periudha I",""],["Era Gashi","VIII/1","Matematikë","Detyrë shtëpie","4","Periudha I",""],["Diar Berisha","VIII/2","Matematikë","Aktivitet në klasë","5","Periudha I",""],["Suela Hoxha","VIII/2","Matematikë","Test","5","Periudha I",""]];
data.absences = [["Ardit Krasniqi","VIII/1","14.09.2026","Matematikë","E pajustifikuar",""],["Era Gashi","VIII/1","16.09.2026","Matematikë","E arsyetuar",""]];
defs.grades=["Vlerësimi dhe notat",["Nxënësi","Klasa","Lënda","Lloji i vlerësimit","Nota","Periudha"],data.teacherGrades];
defs.absences=["Mungesat",["Nxënësi","Klasa","Data","Lënda","Statusi"],data.absences];
icons.absences="📝";
configs.MESIMDHENES[1]=[["Klasat","3"],["Nxënës","74"],["Lënda","Matematikë"],["Vlerësime për t'u regjistruar","16"]];
configs.MESIMDHENES[2]=[["classes","Klasat e mia","VIII/1, VIII/2 dhe IX/1."],["students","Nxënësit","Nxënësit e klasave që mëson."],["grades","Vlerësimi dhe notat","Regjistro dhe kontrollo notat."],["absences","Mungesat","Regjistro dhe arsyeto mungesat."],["schedule","Orari","Orari yt i Matematikës."],["announcements","Njoftimet","Njoftimet e shkollës."],["profile","Profili","Të dhënat personale."]];
const teacherStudents=[["Ardit Krasniqi","VIII/1"],["Era Gashi","VIII/1"],["Diar Berisha","VIII/2"],["Suela Hoxha","VIII/2"],["Majlinda Berisha","IX/1"],["Aron Krasniqi","IX/1"]];
function teacherModal(title,body,onSubmit){document.getElementById("teacherModal")?.remove();const el=document.createElement("div");el.id="teacherModal";el.innerHTML=`<div class="teacher-modal-backdrop"><div class="teacher-modal"><div class="teacher-modal-head"><h3>${esc(title)}</h3><button type="button" id="teacherModalClose">×</button></div><form id="teacherModalForm">${body}<div class="teacher-form-actions"><button type="button" id="teacherCancel">Anulo</button><button type="submit" class="primary-button">Ruaj</button></div></form></div></div>`;document.body.appendChild(el);document.getElementById("teacherModalClose").onclick=()=>el.remove();document.getElementById("teacherCancel").onclick=()=>el.remove();document.getElementById("teacherModalForm").onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.target));};}
const field=(label,name,html)=>`<label class="teacher-field"><span>${esc(label)}</span>${html}</label>`;const selectHtml=(name,options)=>`<select name="${esc(name)}" required>${options.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join("")}</select>`;
function addTeacherGrade(){teacherModal("Regjistro vlerësim",[field("Nxënësi","student",selectHtml("student",teacherStudents.map(x=>`${x[0]}|${x[1]}`))),field("Lënda","subject",`<input name="subject" value="Matematikë" readonly>`),field("Lloji i vlerësimit","type",selectHtml("type",["Test","Detyrë shtëpie","Aktivitet në klasë","Pjesëmarrje","Projekt"])),field("Nota","grade",selectHtml("grade",["1","2","3","4","5"])),field("Periudha","period",selectHtml("period",["Periudha I","Periudha II","Periudha III"])),field("Shënim","note",`<textarea name="note" rows="3"></textarea>`)].join(""),fd=>{const p=fd.get("student").split("|");data.teacherGrades.unshift([p[0],p[1],"Matematikë",fd.get("type"),fd.get("grade"),fd.get("period"),fd.get("note")||""]);defs.grades[2]=data.teacherGrades;document.getElementById("teacherModal").remove();module("grades");});}
function addTeacherAbsence(){teacherModal("Regjistro mungesë",[field("Nxënësi","student",selectHtml("student",teacherStudents.map(x=>`${x[0]}|${x[1]}`))),field("Data","date",`<input name="date" type="date" value="2026-09-13" required>`),field("Lënda","subject",`<input name="subject" value="Matematikë" readonly>`),field("Statusi","status",selectHtml("status",["E pajustifikuar","E arsyetuar"])),field("Shënim","note",`<textarea name="note" rows="3"></textarea>`)].join(""),fd=>{const p=fd.get("student").split("|");const d=String(fd.get("date")).split("-").reverse().join(".");data.absences.unshift([p[0],p[1],d,"Matematikë",fd.get("status"),fd.get("note")||""]);defs.absences[2]=data.absences;document.getElementById("teacherModal").remove();module("absences");});}
function teacherActionButtons(k){if(k!=="grades"&&k!=="absences")return;document.getElementById("teacherModuleActions")?.remove();const box=document.createElement("div");box.id="teacherModuleActions";box.className="teacher-module-actions";box.innerHTML=`<div><strong>${k==="grades"?"Vlerësimi i nxënësve":"Evidenca e mungesave"}</strong><small>${k==="grades"?"Regjistro notën dhe llojin e vlerësimit.":"Regjistro dhe arsyeto mungesat."}</small></div><button class="primary-button" id="teacherAddAction">+ ${k==="grades"?"Regjistro vlerësim":"Regjistro mungesë"}</button>`;document.getElementById("moduleContent")?.parentElement?.insertBefore(box,document.getElementById("moduleContent"));document.getElementById("teacherAddAction").onclick=k==="grades"?addTeacherGrade:addTeacherAbsence;}
const originalModule=module;module=function(k){originalModule(k);teacherActionButtons(k);};const originalDashboard=dashboard;dashboard=function(user){if(user&&user.id==="3")user={...user,username:"leonard.tahiraj",fullName:"Leonard Tahiraj",roleLabel:"Mësimdhënës i Matematikës"};originalDashboard(user);};
document.addEventListener("click",function(event){const button=event.target.closest("#loginButton");if(!button)return;const username=String(document.getElementById("username")?.value||"").trim().toLowerCase();const password=String(document.getElementById("password")?.value||"");if(username!=="leonard.tahiraj")return;event.preventDefault();event.stopImmediatePropagation();const error=document.getElementById("error");if(password!=="123456"){if(error)error.textContent="Fjalëkalimi është i pasaktë. Për demo përdor 123456.";return;}if(error)error.textContent="";dashboard({...demoUsers["leonard.tahiraj"],username:"leonard.tahiraj",fullName:"Leonard Tahiraj",roleLabel:"Mësimdhënës i Matematikës"});},true);
const teacherStyle=document.createElement("style");teacherStyle.textContent=`.teacher-module-actions{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 16px;margin:0 0 14px;border:1px solid #dbe3ef;border-radius:12px;background:#fff}.teacher-module-actions strong{display:block}.teacher-module-actions small{display:block;margin-top:4px;color:#64748b}.primary-button{border:0;border-radius:9px;padding:10px 15px;cursor:pointer;background:#2563eb;color:#fff;font-weight:700}.teacher-modal-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;padding:20px;z-index:9999}.teacher-modal{width:min(620px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.teacher-modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.teacher-modal-head h3{margin:0}.teacher-modal-head button{border:0;background:transparent;font-size:28px;cursor:pointer}.teacher-field{display:block;margin:0 0 12px}.teacher-field span{display:block;font-weight:600;margin-bottom:6px}.teacher-field input,.teacher-field select,.teacher-field textarea{box-sizing:border-box;width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:10px;font:inherit}.teacher-form-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.teacher-form-actions button:first-child{border:1px solid #cbd5e1;background:#fff;border-radius:9px;padding:10px 15px;cursor:pointer}`;document.head.appendChild(teacherStyle);